### ISSUE TITLE
support for pthread_mutex_t

### ISSUE THREAD

**Issue by jvo203** [interkosmos/fortran-unix#1]
A very useful library. Have you got plans to add support for POSIX mutexes? Somehow cannot find pthread_mutex_t neither in the examples nor in the source code.

**Comment by interkosmos** [comment]
POSIX mutexes are on the to-do list and will (hopefully) be added in the next weeks.

**Comment by jvo203** [comment]
Many thanks, I will be eager to give fortran-unix a try once the mutex part is in.

**Comment by interkosmos** [comment]
Mutex support has been added. See [examples/mutes/mutex.f90](https://github.com/interkosmos/fortran-unix/blob/master/examples/mutex/mutex.f90) for an example.

The implementation is a little hacky, but works so far on FreeBSD and CentOS.

**Comment by jvo203** [comment]
Thank you! In the meantime I have switched from CoArray FORTRAN to Julia due to better distributed computing facilities...

**Comment by jvo203** [comment]
Hi, just to let you know that I'm back to the FORTRAN world, will give <c_pthread_mutex_t> a try in the very near future. Hopefully it works in macOS too in addition to Linux.

**Comment by interkosmos** [comment]
I doubt that it will work on macOS. In general, it should be no problem to add the necessary type definitions and preprocessor directives, but I donʼt have access to a macOS system to make the required changes to fortran-unix.

**Comment by jvo203** [comment]
OK, will definitely give it a try during next week. First on Linux, and then see if it works on macOS too (or try to debug it and see why it might not work on macOS). Will keep you posted regarding any errors on macOS.

**Comment by jvo203** [comment]
Judging by this file

https://opensource.apple.com/source/xnu/xnu-201/bsd/sys/types.h.auto.html

macOS appears to be using

```#define __PTHREAD_MUTEX_SIZE__     40```

if ```__POSIX_LIB__``` is not defined.

All the defines:
```
#ifndef __POSIX_LIB__

#define __PTHREAD_SIZE__           596 
#define __PTHREAD_ATTR_SIZE__      36
#define __PTHREAD_MUTEXATTR_SIZE__ 8
#define __PTHREAD_MUTEX_SIZE__     40
#define __PTHREAD_CONDATTR_SIZE__  4
#define __PTHREAD_COND_SIZE__      24
#define __PTHREAD_ONCE_SIZE__      4
```

**Comment by jvo203** [comment]
macOS is a bit opaque. The following program gives an answer on macOS

```__PTHREAD_MUTEX_SIZE__: 56```

```
#include <stdlib.h>
#include <stdio.h>

#include <pthread.h>

int main()
{
	printf("__PTHREAD_MUTEX_SIZE__: %d\n",__PTHREAD_MUTEX_SIZE__);
};
```

gcc test.c -pthread

chris@orion ~ % gcc --version      
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: x86_64-apple-darwin21.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by jvo203** [comment]
PTHREAD_SIZE on macOS is different too:

```
__PTHREAD_SIZE__: 8176
__PTHREAD_MUTEX_SIZE__: 56
```

**Comment by jvo203** [comment]
It seems to have worked on macOS too. Just took the ```unix_pthread.F90``` file only and modified it:

```
#if defined (__linux__)

   integer, parameter :: PTHREAD_SIZE = 8    ! 8 Bytes.
   integer, parameter :: PTHREAD_MUTEX_SIZE = 40   ! 40 Bytes.

#elif defined (__FreeBSD__)

   integer, parameter :: PTHREAD_SIZE = 8    ! 8 Bytes.
   integer, parameter :: PTHREAD_MUTEX_SIZE = 8    ! 8 Bytes.

#elif defined (__macOS__)

   integer, parameter :: PTHREAD_SIZE = 8176    ! 8176 Bytes.
   integer, parameter :: PTHREAD_MUTEX_SIZE = 56    ! 56 Bytes.

#endif
```

Then

```
gfortran -cpp -D__macOS__ src/unix_pthread.f90 mutex.f90 -pthread
chris@orion FITSWEBQLSE % ./a.out      
Starting threads ...
Thread  1 changes value from ** to  1
Thread 14 changes value from  1 to 14
Thread  2 changes value from 14 to  2
Thread 15 changes value from  2 to 15
Joining threads ...
Thread 16 changes value from 15 to 16
Thread  6 changes value from 16 to  6
Thread  7 changes value from  6 to  7
Thread  8 changes value from  7 to  8
Thread  9 changes value from  8 to  9
Thread 10 changes value from  9 to 10
Thread 11 changes value from 10 to 11
```

Since I am not planning on using the whole fortran-unix, just added the most interesting unix_pthread.f90 source file to my project. This way different compilers (i.e. gfortran or ifort) can be used interchangeably to compile my entire project.

By the way, ```__PTHREAD_SIZE__``` seems really large on macOS.

**Comment by interkosmos** [comment]
Good to hear it works.

**Comment by jvo203** [comment]
By the way, is there a reason why in your example "mutex.f90" the "foo" subroutine is recursive? Is it somehow related to the interaction with pthreads? Does it need to be recursive? At least on macOS the code seems to work fine with or without the ```recursive``` keyword.

```recursive subroutine foo(arg) bind(c)```

**Comment by interkosmos** [comment]
The `recursive` attribute is optional for procedures called from multiple threads since Fortran 2018. For older compilers, it may still be required.

**Comment by jvo203** [comment]
OK, I see. For now am using the ```recursive``` attribute as per your example. Launching / joining ```pthreads``` works without a hitch on macOS and Linux. Thank you for making this Unix interface available!
